#!/bin/bash
  # Copying files

ROOT_UID=0
DEST_DIR=

# Destination directory
if [ "$UID" -eq "$ROOT_UID" ]; then
  DEST_DIR="/usr/share/themes"
else
  DEST_DIR="$HOME/.themes"
fi

repodir=$(cd $(dirname $0) && pwd)
srcdir=${repodir}/src

  rm -rf $DEST_DIR/Azure*

# Copying files
for trans in '' '-solid' ; do
  for color in '' '-light' ; do
	echo -e "   Installing Azure${trans}${color} ..."

	themedir=$DEST_DIR/Azure${trans}${color}
	install -d ${themedir}

	# Install index.theme
	cd ${srcdir}
	cp -ur \
	index${trans}${color}.theme \
	${themedir}/index.theme

	# Install GNOME Shell Theme
	install -d ${themedir}/gnome-shell
	cd ${srcdir}/gnome-shell
	cp -ur \
	extensions \
	no-events.svg \
	no-notifications.svg \
	process-working.svg \
	${themedir}/gnome-shell

	cp -ur \
		assets${color} \
		${themedir}/gnome-shell/assets

	cp -ur \
		gnome-shell${color}.css \
		${themedir}/gnome-shell/gnome-shell.css

		glib-compile-resources \
		--sourcedir=${themedir}/gnome-shell \
		--target=${themedir}/gnome-shell/gnome-shell-theme.gresource \
		gnome-shell-theme.gresource.xml

	# Install GTK+ 2 Theme
	install -d ${themedir}/gtk-2.0
	cd ${srcdir}/gtk-2.0

	cp -ur \
		gtkrc${color} \
		${themedir}/gtk-2.0/gtkrc

	cp -ur \
		assets \
		apps.rc \
		main.rc \
		panel.rc \
		xfce-notify.rc \
		menubar-toolbar \
		${themedir}/gtk-2.0

	cp -ur \
		menubar-toolbar${color}.rc \
		${themedir}/gtk-2.0/menubar-toolbar/menubar-toolbar.rc 

	# Install GTK+ 3 Theme
	install -d ${themedir}/gtk-3.0
	cd ${srcdir}/gtk-3.0
	cp -ur \
		assets \
		${themedir}/gtk-3.0

	cp -ur \
		thumbnail${color}.png \
		${themedir}/gtk-3.0/thumbnail.png

	cp -ur \
		gtk${trans}${color}.css \
		${themedir}/gtk-3.0/gtk.css

	cp -ur \
		gtk${trans}-dark.css \
		${themedir}/gtk-3.0/gtk-dark.css

	# Install Metacity Theme
	install -d ${themedir}/metacity-1
	cd ${srcdir}/metacity-1
	cp -ur \
		*.svg \
		${themedir}/metacity-1

	cp -ur \
		metacity-theme-1${color}.xml \
		${themedir}/metacity-1/metacity-theme-1.xml
	cp -ur \
		metacity-theme-2${color}.xml \
		${themedir}/metacity-1/metacity-theme-2.xml

	# Install Unity Theme
	install -d ${themedir}/unity
	cd ${srcdir}/unity
	cp -ur \
		*.svg \
		dash \
		${themedir}/unity

	cp -ur \
		window-buttons${color} \
		${themedir}/unity/window-buttons

  done
done



